name: Debian 64-bit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v2
      with:
       repository: alcz/harbour
       path: harbour

    - name: Install dependencies
      run: |
         sudo apt install libcurl4-openssl-dev libssl-dev gcc
         sudo cp -r /usr/include/x86_64-linux-gnu/curl /usr/include
         
    - name: Compile harbour
      run: |
        cd harbour
        export HB_WITH_PCRE=local
        make
